name: On Pull Request
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main
      - beta

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/install.yml
    with:
      node_version: 20

  validations:
    name: Validations
    needs: [ install ]
    uses: ./.github/workflows/validations.yml
    with:
      node_version: 20

  visual_tests:
    name: Visual Regression Tests
    needs: [ validations ]
    if: ${{ !(contains(github.event.head_commit.message, 'chore') || contains(github.event.head_commit.message, 'ci')) }}
    uses: ./.github/workflows/visual-test.yml
    with:
      node_version: 20

  dependabot-automerge:
    name: Dependabot Automerge
    needs: [ install, validations ]
    uses: ./.github/workflows/dependabot-auto-merge.yml
