name: Release
on:
  workflow_dispatch:

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/install.yml
    with:
      node_version: 20

  validations:
    name: Validations
    needs: [ install ]
    uses: ./.github/workflows/validations.yml
    with:
      node_version: 20

  publish_packages:
    name: Publish Packages
    needs: [ validations ]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    uses: ./.github/workflows/publish.yml
    with:
      node_version: 20
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
